### ISSUE TITLE
Using ccxws in browser

### ISSUE THREAD

**Issue by amit-kukadia** [altangent/ccxws#134] opened 2020-01-27 15:55 UTC
Since we are using the ws module, we cannot use the the library in browser. If we can detect if the library is used nodejs or browser, and dynamically use the compatible websocket client, we can use the module on client side aswell. Something like [this](https://www.npmjs.com/package/is-node) can be used i think.

A popular use case could be realtime charts since Candles api is also developed for some exchanges.

**Comment by ejfrancis** [comment] 2020-03-17 19:25
duplicate of #17, can you please close tehis?

**Closed** 2020-03-18 06:13 UTC
